version: "3.8"
services:
  client:
    build: .
    container_name: vue_client
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/src/app
    command: sh -c "npm install && npm run dev"
    env_file: .env
  

